name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build and Publish Image
    runs-on: ubuntu-latest
    concurrency: deploy-group

    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get package version
        id: version
        run: |
          echo ::set-output name=version::$(grep -o '"version": *"[^"]*' package.json | awk -F'"' '{print $4}')

      - run: docker build --tag hasanify/utilities-api:${{ steps.version.outputs.version }} --tag hasanify/utilities-api:latest .
      - run: docker push hasanify/utilities-api:${{ steps.version.outputs.version }}
      - run: docker push hasanify/utilities-api:latest
